CREATE TABLE "finance-ai_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "finance-ai_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "finance-ai_budget" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"amount" numeric(19, 4) NOT NULL,
	"period" varchar(20) NOT NULL,
	"startDate" timestamp with time zone NOT NULL,
	"endDate" timestamp with time zone,
	"categoryId" uuid,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "finance-ai_category" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"color" varchar(7) DEFAULT '#000000' NOT NULL,
	"icon" varchar(255),
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "finance-ai_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance-ai_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "finance-ai_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "finance-ai_transaction" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"amount" numeric(19, 4) NOT NULL,
	"description" varchar(255) NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"isRecurring" boolean DEFAULT false NOT NULL,
	"userId" varchar(255) NOT NULL,
	"categoryId" uuid,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "finance-ai_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"subscriptionTier" varchar(50) DEFAULT 'free' NOT NULL,
	CONSTRAINT "finance-ai_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "finance-ai_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "finance-ai_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "finance-ai_account" ADD CONSTRAINT "finance-ai_account_userId_finance-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."finance-ai_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_budget" ADD CONSTRAINT "finance-ai_budget_categoryId_finance-ai_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."finance-ai_category"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_budget" ADD CONSTRAINT "finance-ai_budget_userId_finance-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."finance-ai_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_category" ADD CONSTRAINT "finance-ai_category_userId_finance-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."finance-ai_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_post" ADD CONSTRAINT "finance-ai_post_createdById_finance-ai_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."finance-ai_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_session" ADD CONSTRAINT "finance-ai_session_userId_finance-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."finance-ai_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_transaction" ADD CONSTRAINT "finance-ai_transaction_userId_finance-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."finance-ai_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance-ai_transaction" ADD CONSTRAINT "finance-ai_transaction_categoryId_finance-ai_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."finance-ai_category"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "finance-ai_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "budget_user_id_idx" ON "finance-ai_budget" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "budget_category_id_idx" ON "finance-ai_budget" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "category_user_id_idx" ON "finance-ai_category" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "category_name_idx" ON "finance-ai_category" USING btree ("name");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "finance-ai_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "finance-ai_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "finance-ai_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transaction_user_id_idx" ON "finance-ai_transaction" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transaction_category_id_idx" ON "finance-ai_transaction" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "transaction_date_idx" ON "finance-ai_transaction" USING btree ("date");